"""Plugin Factory - Self-Building Meta-Plugin.

This is the most advanced example: a plugin that creates other plugins.
It demonstrates the self-extending nature of the PMS platform.

Key Concepts:
1. Meta-programming: Generating code that generates code
2. Self-building: The system can extend itself
3. Template-based generation: Standardized patterns
4. Dynamic registration: New plugins become available immediately

Usage Examples:

    # Create a simple plugin from description
    pms plugin call plugin-factory.create_plugin \
        --arg name=my-utils \
        --arg description="Utility functions for my workflow" \
        --arg tools='[{"name": "format_date", "description": "Format a date string"}]'

    # Generate DSL tools file
    pms plugin call plugin-factory.create_dsl_tools \
        --arg name=math-helpers \
        --arg tools='[{"name": "percent", "description": "Calculate percentage", "logic": "x / total * 100"}]'

    # Create from template
    pms plugin call plugin-factory.create_from_template \
        --arg template=api-integration \
        --arg name=slack-integration \
        --arg config='{"api_base": "https://slack.com/api"}'

    # Analyze code and generate plugin
    pms plugin call plugin-factory.analyze_and_generate \
        --arg source=./my_module.py \
        --arg plugin_name=my-module-tools

The Self-Building Philosophy:
    The most powerful systems are those that can improve themselves.
    By enabling plugins to create plugins, PMS becomes an infinitely
    extensible platform where new capabilities emerge organically.

    Think of it as: "I need a tool to do X" -> instant tool creation
    without leaving the workflow.
"""

import json
import re
from datetime import datetime
from pathlib import Path
from textwrap import indent
from typing import Any

# =============================================================================
# Configuration
# =============================================================================

_config = {
    "output_directory": "~/.pms/plugins",
    "auto_register": True,
}

# Plugin templates
TEMPLATES = {
    "api-integration": {
        "description": "Template for REST API integrations",
        "capabilities": ["network"],
        "default_tools": ["list", "get", "create", "update", "delete"],
    },
    "file-processor": {
        "description": "Template for file processing plugins",
        "capabilities": ["filesystem_read", "filesystem_write"],
        "default_tools": ["process", "validate", "transform", "batch"],
    },
    "automation": {
        "description": "Template for automation/workflow plugins",
        "capabilities": ["events", "subprocess"],
        "default_tools": ["run", "schedule", "trigger", "status"],
    },
    "data-transformer": {
        "description": "Template for data transformation plugins",
        "capabilities": [],
        "default_tools": ["transform", "validate", "convert", "aggregate"],
    },
}


# =============================================================================
# Code Generation Helpers
# =============================================================================


def _generate_manifest(
    name: str,
    description: str,
    tools: list[dict],
    capabilities: list[str] = None,
    config_schema: dict = None,
) -> dict:
    """Generate a plugin manifest."""
    manifest = {
        "name": name,
        "version": "1.0.0",
        "description": description,
        "author": "Generated by plugin-factory",
        "type": "extension",
        "entrypoint": "main.py",
        "sandbox": bool(capabilities),
        "tools": [],
    }

    if capabilities:
        manifest["capabilities"] = capabilities

    for tool in tools:
        tool_def = {
            "name": tool["name"],
            "description": tool.get("description", f"The {tool['name']} tool"),
        }

        if "params" in tool or "parameters" in tool:
            params = tool.get("params") or tool.get("parameters", {})
            tool_def["parameters"] = {}
            for param_name, param_info in params.items():
                if isinstance(param_info, str):
                    tool_def["parameters"][param_name] = {
                        "type": param_info,
                        "required": True,
                    }
                else:
                    tool_def["parameters"][param_name] = param_info

        manifest["tools"].append(tool_def)

    if config_schema:
        manifest["config_schema"] = config_schema

    return manifest


def _generate_tool_code(
    name: str,
    description: str,
    parameters: dict = None,
    implementation: str = None,
) -> str:
    """Generate Python code for a tool function."""
    # Build parameter signature
    params = []
    param_docs = []

    if parameters:
        for param_name, param_info in parameters.items():
            if isinstance(param_info, str):
                param_type = param_info
                required = True
                default = None
                param_desc = ""
            else:
                param_type = param_info.get("type", "str")
                required = param_info.get("required", True)
                default = param_info.get("default")
                param_desc = param_info.get("description", "")

            # Python type mapping
            type_map = {
                "string": "str",
                "int": "int",
                "integer": "int",
                "float": "float",
                "bool": "bool",
                "boolean": "bool",
                "list": "list",
                "dict": "dict",
            }
            py_type = type_map.get(param_type, "Any")

            if required:
                params.append(f"{param_name}: {py_type}")
            else:
                default_repr = repr(default) if default is not None else "None"
                params.append(f"{param_name}: {py_type} = {default_repr}")

            param_docs.append(f"        {param_name}: {param_desc}")

    params_str = ", ".join(params) if params else ""
    params_doc = "\n".join(param_docs) if param_docs else "        None"

    # Default implementation
    if not implementation:
        implementation = f'''
    # TODO: Implement {name}
    return {{"status": "ok", "tool": "{name}"}}
'''

    code = f'''
async def {name}({params_str}) -> dict[str, Any]:
    """{description}

    Args:
{params_doc}

    Returns:
        Result dictionary
    """
{indent(implementation.strip(), "    ")}
'''
    return code


def _generate_main_py(
    plugin_name: str,
    description: str,
    tools: list[dict],
) -> str:
    """Generate complete main.py for a plugin."""
    header = f'''"""{plugin_name} - Auto-generated plugin.

{description}

Generated by plugin-factory at {datetime.now().isoformat()}

Usage:
    pms plugin start {plugin_name}
'''

    # Add tool usage examples
    for tool in tools:
        header += f"    pms plugin call {plugin_name}.{tool['name']}\n"

    header += '"""\n\nfrom typing import Any\n\n'

    # Generate each tool
    tool_code = ""
    for tool in tools:
        tool_code += _generate_tool_code(
            name=tool["name"],
            description=tool.get("description", ""),
            parameters=tool.get("params") or tool.get("parameters"),
            implementation=tool.get("implementation"),
        )
        tool_code += "\n"

    # Add lifecycle hooks
    lifecycle = '''
# =============================================================================
# Lifecycle Hooks
# =============================================================================


async def on_load(config: dict = None):
    """Initialize plugin."""
    print(f"[{plugin_name}] Plugin loaded")


async def on_unload():
    """Cleanup plugin."""
    print(f"[{plugin_name}] Plugin unloaded")
'''

    return header + tool_code + lifecycle.replace("{plugin_name}", plugin_name)


def _generate_dsl_file(name: str, tools: list[dict]) -> str:
    """Generate a .tools DSL file."""
    content = f"""## {name} - Auto-generated DSL tools
##
## Generated by plugin-factory at {datetime.now().isoformat()}
##
## Usage:
##     pms plugin discover <directory>
"""

    for tool in tools:
        content += f"""
tool {tool["name"]}:
    description: "{tool.get("description", "")}"
    return {tool.get("logic", "42")}
"""

    return content


# =============================================================================
# Tool Implementations
# =============================================================================


async def create_plugin(
    name: str,
    description: str,
    tools: list[dict],
    output_dir: str = None,
) -> dict[str, Any]:
    """Generate a complete plugin from specifications.

    This is the core self-building capability: describe what you need,
    and a working plugin is created.

    Args:
        name: Plugin name (lowercase, hyphens allowed)
        description: What the plugin should do
        tools: List of tool definitions
        output_dir: Where to create the plugin

    Returns:
        Information about the created plugin
    """
    # Validate name
    if not re.match(r"^[a-z][a-z0-9-]*$", name):
        return {
            "success": False,
            "error": "Invalid plugin name. Use lowercase letters, numbers, hyphens.",
        }

    # Determine output directory
    output = Path(output_dir or _config["output_directory"]).expanduser()
    plugin_dir = output / name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Generate manifest
    manifest = _generate_manifest(name, description, tools)
    manifest_path = plugin_dir / "plugin.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))

    # Generate main.py
    main_code = _generate_main_py(name, description, tools)
    main_path = plugin_dir / "main.py"
    main_path.write_text(main_code)

    # Create README
    readme = f"""# {name}

{description}

## Installation

```bash
pms plugin discover {output}
pms plugin start {name}
```

## Tools

"""
    for tool in tools:
        readme += f"### {tool['name']}\n\n{tool.get('description', '')}\n\n"

    readme_path = plugin_dir / "README.md"
    readme_path.write_text(readme)

    return {
        "success": True,
        "plugin_name": name,
        "path": str(plugin_dir),
        "files": ["plugin.json", "main.py", "README.md"],
        "tools": [t["name"] for t in tools],
        "next_steps": [
            f"pms plugin discover {output}",
            f"pms plugin start {name}",
        ],
    }


async def create_tool(
    plugin_name: str,
    tool_name: str,
    description: str,
    parameters: dict = None,
    implementation: str = None,
) -> dict[str, Any]:
    """Add a new tool to an existing plugin.

    Enables incremental plugin development - add tools as needed.

    Args:
        plugin_name: Name of existing plugin
        tool_name: Name for new tool
        description: Tool description
        parameters: Tool parameters
        implementation: Python code for implementation

    Returns:
        Status of tool creation
    """
    output = Path(_config["output_directory"]).expanduser()
    plugin_dir = output / plugin_name

    if not plugin_dir.exists():
        return {
            "success": False,
            "error": f"Plugin {plugin_name} not found at {plugin_dir}",
        }

    # Update manifest
    manifest_path = plugin_dir / "plugin.json"
    manifest = json.loads(manifest_path.read_text())

    # Check for duplicate
    existing_tools = [t["name"] for t in manifest.get("tools", [])]
    if tool_name in existing_tools:
        return {
            "success": False,
            "error": f"Tool {tool_name} already exists in {plugin_name}",
        }

    # Add tool to manifest
    tool_def = {
        "name": tool_name,
        "description": description,
    }
    if parameters:
        tool_def["parameters"] = parameters

    manifest["tools"].append(tool_def)
    manifest_path.write_text(json.dumps(manifest, indent=2))

    # Add to main.py
    main_path = plugin_dir / "main.py"
    main_code = main_path.read_text()

    new_tool_code = _generate_tool_code(
        name=tool_name,
        description=description,
        parameters=parameters,
        implementation=implementation,
    )

    # Insert before lifecycle hooks
    if "# Lifecycle Hooks" in main_code:
        main_code = main_code.replace(
            "# Lifecycle Hooks",
            new_tool_code + "\n# Lifecycle Hooks",
        )
    else:
        main_code += new_tool_code

    main_path.write_text(main_code)

    return {
        "success": True,
        "plugin": plugin_name,
        "tool": tool_name,
        "message": f"Added tool {tool_name} to {plugin_name}",
        "restart_required": True,
    }


async def create_dsl_tools(
    name: str,
    tools: list[dict],
    output_dir: str = None,
) -> dict[str, Any]:
    """Generate a DSL tools file.

    The simplest form of plugin creation - no Python needed,
    just declarative tool definitions.

    Args:
        name: Name for the tools file (without extension)
        tools: List of {name, description, logic} objects
        output_dir: Where to save the file

    Returns:
        Information about created file
    """
    output = Path(output_dir or _config["output_directory"]).expanduser()
    output.mkdir(parents=True, exist_ok=True)

    content = _generate_dsl_file(name, tools)
    file_path = output / f"{name}.tools"
    file_path.write_text(content)

    return {
        "success": True,
        "file": str(file_path),
        "tools": [t["name"] for t in tools],
        "next_steps": [
            f"pms plugin discover {output}",
            f"pms plugin call {name}.<tool_name>",
        ],
    }


async def analyze_and_generate(
    source: str,
    plugin_name: str,
) -> dict[str, Any]:
    """Analyze source code and generate a plugin for it.

    Advanced self-building: examine existing code and create
    tools that expose its functionality.

    Args:
        source: Path to Python file or directory
        plugin_name: Name for generated plugin

    Returns:
        Generated plugin information
    """
    source_path = Path(source).expanduser()

    if not source_path.exists():
        return {"success": False, "error": f"Source not found: {source}"}

    # Simple analysis: find async functions
    tools = []

    if source_path.is_file():
        files = [source_path]
    else:
        files = list(source_path.glob("**/*.py"))

    for file_path in files:
        try:
            content = file_path.read_text()

            # Find function definitions (simple regex, not full AST)
            pattern = r"async def (\w+)\((.*?)\).*?(?:\"\"\"(.*?)\"\"\")?.*?:"
            matches = re.findall(pattern, content, re.DOTALL)

            for match in matches:
                func_name, params, docstring = match
                if not func_name.startswith("_"):  # Skip private functions
                    tools.append(
                        {
                            "name": func_name,
                            "description": docstring.split("\n")[0]
                            if docstring
                            else f"Wrapper for {func_name}",
                            "implementation": f"# TODO: Call original {func_name}\nreturn {{}}",
                        }
                    )
        except Exception:
            pass  # Skip unreadable files

    if not tools:
        return {
            "success": False,
            "error": "No suitable functions found in source",
        }

    # Generate the plugin
    return await create_plugin(
        name=plugin_name,
        description=f"Auto-generated from {source}",
        tools=tools,
    )


async def list_templates() -> dict[str, Any]:
    """List available plugin templates."""
    return {
        "templates": {
            name: {
                "description": info["description"],
                "capabilities": info["capabilities"],
                "default_tools": info["default_tools"],
            }
            for name, info in TEMPLATES.items()
        }
    }


async def create_from_template(
    template: str,
    name: str,
    config: dict = None,
) -> dict[str, Any]:
    """Create a plugin from a predefined template.

    Templates provide proven patterns for common use cases.

    Args:
        template: Template name
        name: Plugin name
        config: Template-specific configuration

    Returns:
        Created plugin information
    """
    if template not in TEMPLATES:
        return {
            "success": False,
            "error": f"Unknown template: {template}",
            "available": list(TEMPLATES.keys()),
        }

    template_info = TEMPLATES[template]
    config = config or {}

    # Generate tools based on template
    tools = []
    for tool_name in template_info["default_tools"]:
        tools.append(
            {
                "name": tool_name,
                "description": f"{tool_name.title()} operation",
                "params": {"input": "string"},
            }
        )

    return await create_plugin(
        name=name,
        description=f"{name} - created from {template} template",
        tools=tools,
    )


# =============================================================================
# Lifecycle
# =============================================================================


async def on_load(config: dict = None):
    """Initialize the plugin factory."""
    global _config
    if config:
        _config.update(config)

    output = Path(_config["output_directory"]).expanduser()
    output.mkdir(parents=True, exist_ok=True)

    print(f"[plugin-factory] Ready to create plugins at {output}")
    print(
        "[plugin-factory] Use 'pms plugin call plugin-factory.list_templates' to see options"
    )


async def on_unload():
    """Cleanup."""
    print("[plugin-factory] Plugin factory unloaded")
