"""Helpers for classifying generated ephemeral PMS artifacts."""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime, timedelta

from pms.models import Goal, Plan, Project

_PLACEHOLDER_REFERENCE_VALUES = {"", "null", "none", "nil", "undefined"}
_RUNTIME_REPRO_PROJECT_RE = re.compile(r"^Runtime Repro Project(?: \d+)?$")
_COMPLETE_REPRO_PROJECT_RE = re.compile(r"^Complete Repro Project(?: \d+)?$")
_BENCHMARK_PROJECT_RE = re.compile(r"^Bench Project(?: \d+)?$")
_FILTER_FIXTURE_PROJECT_NAMES = {
    "Goal Filter Project A",
    "Goal Filter Project B",
    "Objective Filter Project",
    "Key Result Filter Project",
}
_RECENT_PROGRESS_FIXTURE_MAX_AGE = timedelta(hours=12)


def _looks_like_placeholder_reference(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in _PLACEHOLDER_REFERENCE_VALUES


def is_placeholder_reference(value: str | None) -> bool:
    """Return whether a linked ID/value is just a serialized placeholder."""
    return _looks_like_placeholder_reference(value)


def _looks_like_quickstart_fixture_project(project: Project) -> bool:
    if project.name == "Quickstart Project":
        return True
    if project.name == "Output Fix Validation Project":
        return True
    if _RUNTIME_REPRO_PROJECT_RE.match(project.name):
        return True
    return bool(
        project.description == "Quickstart project"
        and _COMPLETE_REPRO_PROJECT_RE.match(project.name)
    )


def _looks_like_audit_fixture_project(project: Project) -> bool:
    return project.name in {"Audit Active Project", "Modeling Hints Audit Project"}


def _looks_like_repro_fixture_project(project: Project) -> bool:
    if project.name == "Blocked Active Dependency Project":
        return True
    if _RUNTIME_REPRO_PROJECT_RE.match(project.name):
        return True
    return bool(_COMPLETE_REPRO_PROJECT_RE.match(project.name))


def _looks_like_benchmark_fixture_project(project: Project) -> bool:
    return bool(_BENCHMARK_PROJECT_RE.match(project.name))


def _looks_like_filter_fixture_project(project: Project) -> bool:
    return project.name in _FILTER_FIXTURE_PROJECT_NAMES


def _project_datetime_utc(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _looks_like_stale_recent_progress_fixture_project(project: Project) -> bool:
    if project.name != "Recent Progress Project":
        return False
    last_activity = _project_datetime_utc(project.updated_at) or _project_datetime_utc(
        project.created_at
    )
    if last_activity is None:
        return False
    return datetime.now(UTC) - last_activity >= _RECENT_PROGRESS_FIXTURE_MAX_AGE


def _looks_like_runtime_fixture_plan(plan: Plan) -> bool:
    if plan.name == "Draft Locked Dependent Plan":
        return True
    if plan.name in {"Draft Progress Plan", "Draft Start Plan"}:
        return True
    return plan.name.endswith(" Plan") and (
        _RUNTIME_REPRO_PROJECT_RE.match(plan.name.removesuffix(" Plan"))
        or _COMPLETE_REPRO_PROJECT_RE.match(plan.name.removesuffix(" Plan"))
    )


def _looks_like_placeholder_linked_plan(plan: Plan) -> bool:
    return any(
        _looks_like_placeholder_reference(value)
        for value in (plan.project_id, plan.goal_id, plan.objective_id, plan.product_id)
    )


def is_quickstart_generated_plan(
    plan: Plan,
    plan_name: str | None = None,
) -> bool:
    """Return whether a plan looks like a generated quickstart plan."""
    if plan_name is not None and plan.name != plan_name:
        return False
    if "quickstart" in plan.tags:
        return True
    if plan.description == "Quickstart plan":
        return True
    try:
        content = json.loads(plan.content)
    except json.JSONDecodeError:
        return False
    if not isinstance(content, dict):
        return False
    return content.get("summary") == "Starter plan generated by quickstart."


def is_audit_generated_project(project: Project) -> bool:
    """Return whether a project should be hidden from default operator views."""
    tags = set(project.tags or [])
    if {"audit", "audit-generated"} & tags:
        return True
    if project.name.startswith("Audit Project "):
        return True
    if _looks_like_audit_fixture_project(project):
        return True
    return bool(_looks_like_quickstart_fixture_project(project))


def classify_project_operator_category(
    project: Project,
    *,
    effective_status: str | None = None,
) -> str:
    """Classify a project for operator-facing list/dashboard grouping."""
    if is_audit_generated_project(project):
        return "audit_artifact"
    if _looks_like_benchmark_fixture_project(project):
        return "benchmark_artifact"
    if _looks_like_repro_fixture_project(project):
        return "repro_artifact"
    if _looks_like_filter_fixture_project(project):
        return "project_history"
    if _looks_like_stale_recent_progress_fixture_project(project):
        return "project_history"
    status_value = effective_status or project.status.value
    if status_value == "active":
        return "active_work"
    if project.name.startswith("PMS "):
        return "delivery_history"
    return "project_history"


_PROJECT_OPERATOR_CATEGORY_LABELS = {
    "active_work": "Active Work",
    "delivery_history": "Delivery History",
    "benchmark_artifact": "Benchmark Artifact",
    "repro_artifact": "Repro Artifact",
    "audit_artifact": "Audit Artifact",
    "project_history": "Project History",
}


_PROJECT_OPERATOR_CATEGORY_REASONS = {
    "active_work": "current actionable work",
    "delivery_history": "completed delivery reference",
    "benchmark_artifact": "performance proof/reference",
    "repro_artifact": "defect repro/reference",
    "audit_artifact": "audit/regression reference",
    "project_history": "retained historical lookup",
}

_PROJECT_OPERATOR_CATEGORY_COMPACT_LABELS = {
    "active_work": "Active",
    "delivery_history": "Delivery",
    "benchmark_artifact": "Benchmark",
    "repro_artifact": "Repro",
    "audit_artifact": "Audit",
    "project_history": "History",
}

_PROJECT_OPERATOR_CATEGORY_COMPACT_REASONS = {
    "active_work": "actionable",
    "delivery_history": "delivery ref",
    "benchmark_artifact": "benchmark ref",
    "repro_artifact": "repro ref",
    "audit_artifact": "audit ref",
    "project_history": "history ref",
}


def project_operator_category_label(category: str) -> str:
    """Return a human-facing label for a project operator category."""
    return _PROJECT_OPERATOR_CATEGORY_LABELS.get(
        category,
        category.replace("_", " ").title(),
    )


def project_operator_visibility_reason(category: str) -> str:
    """Return a compact explanation for why a categorized project is visible."""
    return _PROJECT_OPERATOR_CATEGORY_REASONS.get(
        category, "retained for operator lookup"
    )


def project_operator_category_compact_label(category: str) -> str:
    """Return a short human-facing label for dense table rendering."""
    return _PROJECT_OPERATOR_CATEGORY_COMPACT_LABELS.get(
        category,
        project_operator_category_label(category),
    )


def project_operator_visibility_compact_reason(category: str) -> str:
    """Return a short visibility reason for dense table rendering."""
    return _PROJECT_OPERATOR_CATEGORY_COMPACT_REASONS.get(
        category,
        project_operator_visibility_reason(category),
    )


def is_audit_generated_plan(
    plan: Plan,
    project_name: str | None = None,
) -> bool:
    """Return whether a plan should be hidden from default operator views."""
    tags = set(plan.tags or [])
    if {"audit", "audit-generated"} & tags:
        return True
    if plan.name.startswith("Audit Plan "):
        return True
    if project_name and project_name.startswith("Audit Project "):
        return True
    if _looks_like_runtime_fixture_plan(plan):
        return True
    if _looks_like_placeholder_linked_plan(plan):
        return True
    if project_name == "Audit Active Project":
        return True
    if project_name == "Output Fix Validation Project":
        return True
    return bool(
        project_name
        and (
            _RUNTIME_REPRO_PROJECT_RE.match(project_name)
            or _COMPLETE_REPRO_PROJECT_RE.match(project_name)
        )
    )


def is_audit_generated_goal(
    goal: Goal,
    *,
    project_name: str | None = None,
) -> bool:
    """Return whether a goal should be hidden from default operator views."""
    tags = set(goal.tags or ())
    if {"audit", "audit-generated"} & tags:
        return True
    if goal.name.startswith("Audit Goal "):
        return True
    if project_name and project_name.startswith("Audit Project "):
        return True
    if project_name in {
        "Quickstart Project",
        "Output Fix Validation Project",
        "Audit Active Project",
    }:
        return True
    return bool(
        project_name
        and (
            _RUNTIME_REPRO_PROJECT_RE.match(project_name)
            or _COMPLETE_REPRO_PROJECT_RE.match(project_name)
        )
    )
