"""Shared defaults for the local PMS server runtime."""

LOCAL_SERVER_DEFAULT_HOST = "127.0.0.1"
LOCAL_SERVER_DEFAULT_PORT = 27541
LOCAL_SERVER_DEFAULT_BASE_URL = (
    f"http://{LOCAL_SERVER_DEFAULT_HOST}:{LOCAL_SERVER_DEFAULT_PORT}"
)
